# Generated by Django 4.0.5 on 2022-07-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVTFernandoMaldonado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermana_mayor',
            name='año_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='hermana_melliza',
            name='año_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='año_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='año_de_nacimiento',
        ),
    ]
